import { ErrorProvider } from "./context/errorContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <ErrorProvider>
          <div className="mainBody">
            {children}
          </div>
        </ErrorProvider>
      </body>
    </html>
  );
}
